name: 'Regula codegen Workflow'
description: 'Run Non-functional Test Agent'
inputs:
  INPUT_FILE_PATH:
    description: 'Path to the input file'
    required: true
  OUTPUT_FILE_PATH:
    description: 'Path to the output file'
    required: true
  PIPELINE_TOKEN:
    description: 'Pipeline token'
    required: true
  VCS_TYPE:
    description: 'Version control system type'
    default: 'github'
runs:
  using: 'docker'
  image: 'docker://docker.io/pranayc/codegen:amd64'
