name: 'Regula testgen Workflow'
description: 'Run Non-functional Test Agent'
inputs:
  input_file_path:
    description: 'Path to the input file'
    required: true
  output_file_path:
    description: 'Path to the output file'
    required: true
  pipeline_token:
    description: 'Pipeline token'
    required: true
  anthropic_api_key:
    description: "Cluade API key"
    required: true
  openai_api_key:
    description: "OpenAI API key"
    required: true
runs:
  using: 'docker'
  image: 'docker://docker.io/pranayc/codegen:github-action'
  env:
    INPUT_FILE_PATH: ${{ inputs.input_file_path }}
    OUTPUT_FILE_PATH: ${{ inputs.output_file_path }}
    PIPELINE_TOKEN: ${{ inputs.pipeline_token }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    FORCE_COLOR: 1
    NODE_OPTIONS: --no-warnings
