name: 'Regula testgen Workflow'
description: 'Run Non-functional Test Agent'
inputs:
  input_file_path:
    description: 'Path to the input file'
    required: true
  output_file_path:
    description: 'Path to the output file'
    required: true
  pipeline_token:
    description: 'Pipeline token'
    required: true
  anthropic_api_key:
    description: "Cluade API key"
    required: true
  openai_api_key:
    description: "OpenAI API key"
    required: true
  pr_workflow:
    description: "whether to run pr workflow on commment or main PR ('pr'|'comment')"
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  aws-bucket:
    description: 'AWS bucket'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/nonfx/starchitect-testgen:github-action'
  env:
    INPUT_FILE_PATH: ${{ inputs.input_file_path }}
    OUTPUT_FILE_PATH: ${{ inputs.output_file_path }}
    PIPELINE_TOKEN: ${{ inputs.pipeline_token }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    PR_WORKFLOW: ${{ inputs.pr_workflow }}
    AWS_REGION: ${{ inputs.aws-region }}
    AWS_BUCKET: ${{ inputs.aws-bucket }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    FORCE_COLOR: 1
    MODEL: "sonnet"
    NODE_OPTIONS: --no-warnings
    OUTPUTDIR: ${{ inputs.output_file_path }}
